### ISSUE TITLE
unable to reach the LCZ Generator is it down? connection has timed out

### ISSUE THREAD

**Issue by scepeda78** [RUBclim/LCZ-Generator-Issues#42]
Hi all, I', trying to connect from Chile, but despite the server indicates 99% uptime, i cannot open the web page. Is there an issue with international connections?

**Comment by theendlessriver13** [comment]
The Outage starting **2022-12-03 05:00 UTC** has been resolved as of **2022-12-08 14:16 UTC**. We are sorry for the inconvenience. The outage was caused by a hardware failure in critical institute wide systems the LCZ Generator depended on.

Submissions made earlier (after **2022-12-03 05:00 UTC**) will be requeued soon. New submissions are possible now.
