### ISSUE TITLE
No data Thin Line Appearing for LCZ Generator for Riyadh

### ISSUE THREAD

**Issue by azmeeram** [RUBclim/LCZ-Generator-Issues#66]
![Riyadh TIF LCZ_Error](https://github.com/user-attachments/assets/2eabdf4f-6153-40a8-91d3-7f7bfee3b006)
Whenever I download the tif file from the LCZ generator for Riyadh City (after submitting training areas there is a thin line above showing no data. Please advice.

**Comment by jkittner** [comment]
please provide more information:
- a link to your submission or your `submission_id`
- what program are you using to open the geotiff

other relevant information to reproduce the issue or at least be able to have a look at it.

**Comment by azmeeram** [comment]
Hi Jonas,

Thanks for your quick reply, Sure.

The submission ID is: ID: 6ead09e6a4cdf648517466af1aac64a245e502a3
https://lcz-generator.rub.de/factsheets/6ead09e6a4cdf648517466af1aac64a245e502a3/6ead09e6a4cdf648517466af1aac64a245e502a3_factsheet.html

I am using ArcGIS to open it. The no data line occurs on QGIS as well.

Thanks,
Amjad Azmeer

**Comment by jkittner** [comment]
Thanks for providing the information. The line you are encountering has values of `0` which means missing data. I am not entirely sure why this is happening, but it is likely due to the underlying EO data - maybe there is a slight mismatch when cropping all the datasets or one of the datasets is missing data in this area.

So for you it safe to exclude these parts of the data. Simply set the value `0` as missing data. The map should still be usable. If you really need the values in this 4 pixel wide strip, you can simply place a few TAs further north to increase the size of you domain in that direction. This will likely not fix the issue with the stripe but will shift it north, so you get proper values in this geographic area.

I hope that helps?
